// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 711 06/05/2020)
// Created on Tue Sep  2 12:35:45 2025

UART_TX UART_TX_inst
(
	.clk_3125(clk_3125_sig) ,	// input  clk_3125_sig
	.parity_bit(parity_bit_sig) ,	// input  parity_bit_sig
	.tx_start(tx_start_sig) ,	// input  tx_start_sig
	.data(data_sig) ,	// input [7:0] data_sig
	.tx(tx_sig) ,	// output  tx_sig
	.tx_done(tx_done_sig) 	// output  tx_done_sig
);

