// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 711 06/05/2020)
// Created on Tue Sep  2 12:47:23 2025

UART_RX UART_RX_inst
(
	.clk_3125(clk_3125_sig) ,	// input  clk_3125_sig
	.rx(rx_sig) ,	// input  rx_sig
	.rx_msg(rx_msg_sig) ,	// output [7:0] rx_msg_sig
	.rx_parity(rx_parity_sig) ,	// output  rx_parity_sig
	.rx_complete(rx_complete_sig) 	// output  rx_complete_sig
);

